# Generated by Django 5.2.4 on 2025-07-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortality', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='life_expectancy',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bmi_category',
            field=models.CharField(choices=[('underweight', 'Underweight (BMI < 18.5)'), ('normal', 'Normal (BMI 18.5-24.9)'), ('overweight', 'Overweight (BMI 25-29.9)'), ('obese', 'Obese (BMI 30+)')], default='normal', max_length=15),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='calculated_life_expectancy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(default='United States', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='drinking_habits',
            field=models.CharField(choices=[('none', 'No alcohol'), ('light', 'Light (1-3 drinks/week)'), ('moderate', 'Moderate (4-14 drinks/week)'), ('heavy', 'Heavy (15+ drinks/week)')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='exercise_frequency',
            field=models.CharField(choices=[('none', 'No regular exercise'), ('light', 'Light (1-2 times/week)'), ('moderate', 'Moderate (3-4 times/week)'), ('heavy', 'Heavy (5+ times/week)')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='family_longevity',
            field=models.IntegerField(default=75, help_text='Average age of death of parents/grandparents'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sleep_quality',
            field=models.CharField(choices=[('poor', 'Poor (< 6 hours)'), ('fair', 'Fair (6-7 hours)'), ('good', 'Good (7-9 hours)'), ('excessive', 'Excessive (9+ hours)')], default='good', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='smoking_status',
            field=models.CharField(choices=[('never', 'Never smoked'), ('former', 'Former smoker'), ('light', 'Light smoker (1-10/day)'), ('moderate', 'Moderate smoker (11-20/day)'), ('heavy', 'Heavy smoker (20+/day)')], default='never', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='social_connections',
            field=models.BooleanField(default=True, help_text='Do you have strong social connections?'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stress_level',
            field=models.IntegerField(default=5, help_text='Stress level 1-10 (10 being extremely stressed)'),
        ),
    ]
